spring:
  cloud:
    openservicebroker:
      catalog:
        services:
        - id: AWS-Services
          name: AWS
          description: A simple example
          bindable: true
          tags:
          - example
          - tags
          plans:
          - id: DEV
            name: M0
            description: Free
          - id: QA
            name: M2
            description: M2 tier
        - id: GCP-service
          name: GCP
          description: A simple example
          bindable: true
          tags:
          - example
          - tags
          plans:
          - id: simple-plan
            name: standard
            description: A simple plan
          - id: simple-plan
            name: standard
            description: A simple plan