spring:
  cloud:
    openservicebroker:
      catalog:
        services:
        - id: First
          name: example
          description: A simple example
          bindable: true
          tags:
          - example
          - tags
          plans:
          - id: simple-plan
            name: standard
            description: imple plan